# -*- coding: utf-8 -*-
"""stock_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wij-jgnJ3hCHc4eGKoDOSl8qka0GlDVL
"""

# ------------------------------------------
# Stock Management Program
# ------------------------------------------
def read_stock(filename):
    """
    Read stock.txt and return the stock as a dictionary.
    Expected file format:
    banana:5
    apple:3
    mango:7
    """

    stock = {}

    try:
        with open(filename, "r") as file:

            for line in file:
                line = line.strip()

                # Ignore empty lines
                if line == "":
                    continue

                # Validate file format
                if "," not in line:
                    raise ValueError("Invalid file format.")

                name, quantity = line.split(",", 1)

                name = name.strip().lower()
                quantity = quantity.strip()

                if name == "":
                    raise ValueError("Stock name cannot be empty.")

                quantity = int(quantity)

                if quantity < 0:
                    raise ValueError(
                        "Stock quantity cannot be negative."
                    )

                stock[name] = quantity

        return stock

    except FileNotFoundError:
        print("Error: stock.txt was not found.")
        print("Starting with an empty stock.")
        return {}

    except ValueError as error:
        print("Error: corrupted file format.")
        print(error)
        print("Starting with an empty stock.")
        return {}

    except Exception as error:
        print("An unexpected error occurred.")
        print(error)
        return {}


# ------------------------------------------
# Show stock
# ------------------------------------------

def show_stock(stock):
    """Print the stock in a readable format."""

    if len(stock) == 0:
        print("\nThe stock is empty.")
        return

    print("\nCurrent Stock:")

    for index, (name, quantity) in enumerate(stock.items(), start=1):
        print(f"{index}. {name}: {quantity}")


# ------------------------------------------
# Get stock name using name or ID
# ------------------------------------------

def get_stock_name(stock, user_input, allow_new=False):
    """
    Return the stock name.

    The user can enter:
    - Stock name, for example: banana
    - Stock ID, for example: 1

    If allow_new is True, a new stock name is allowed.
    """

    user_input = user_input.strip()

    # Check if input is an ID
    if user_input.isdigit():

        stock_id = int(user_input)

        stock_names = list(stock.keys())

        if 1 <= stock_id <= len(stock_names):
            return stock_names[stock_id - 1]

        print("Invalid stock ID.")
        return None

    # Input is a stock name
    else:

        stock_name = user_input.lower()

        # Existing stock
        if stock_name in stock:
            return stock_name

        # New stock is allowed only when adding
        if allow_new:
            return stock_name

        print("This stock does not exist.")
        return None


# ------------------------------------------
# Get a positive integer
# ------------------------------------------

def get_positive_quantity(message):
    """Ask the user for a positive integer."""

    while True:

        try:
            quantity = int(input(message))

            if quantity <= 0:
                print("Please enter a positive number.")
                continue

            return quantity

        except ValueError:
            print("Invalid input. Please enter an integer.")


# ------------------------------------------
# Add stock
# ------------------------------------------

def add_stock(stock):

    # Show stock before adding
    show_stock(stock)

    print("\nEnter a stock name or ID.")
    print("You can also enter a new stock name.")

    user_input = input("Stock name or ID: ")

    stock_name = get_stock_name(
        stock,
        user_input,
        allow_new=True
    )

    # If ID is invalid
    if stock_name is None:
        return

    quantity = get_positive_quantity(
        "How much do you want to add? "
    )

    # If stock already exists
    if stock_name in stock:
        stock[stock_name] += quantity

        print(
            f"{quantity} added to {stock_name}."
        )

    # New stock
    else:
        stock[stock_name] = quantity

        print(
            f"New stock '{stock_name}' added with "
            f"quantity {quantity}."
        )


# ------------------------------------------
# Remove stock
# ------------------------------------------

def remove_stock(stock):

    # Show stock before removing
    show_stock(stock)

    # Cannot remove if stock is empty
    if len(stock) == 0:
        return

    print("\nEnter a stock name or ID.")

    user_input = input("Stock name or ID: ")

    stock_name = get_stock_name(
        stock,
        user_input,
        allow_new=False
    )

    # Invalid name or ID
    if stock_name is None:
        return

    # Ask how much to remove
    while True:

        quantity = get_positive_quantity(
            "How much do you want to remove? "
        )

        # Check that quantity does not become negative
        if stock[stock_name] - quantity < 0:

            print(
                f"Cannot remove {quantity}. "
                f"Only {stock[stock_name]} available."
            )

        else:
            stock[stock_name] -= quantity

            print(
                f"{quantity} removed from {stock_name}."
            )

            break


# ------------------------------------------
# Print menu
# ------------------------------------------

def print_menu():

    print("\n" + "-" * 35)
    print("STOCK MANAGEMENT SYSTEM")
    print("-" * 35)

    print("1. Add stock")
    print("2. Remove stock")
    print("3. Show stock contents")
    print("4. Exit")


# ------------------------------------------
# Get valid menu choice
# ------------------------------------------

def get_menu_choice():

    while True:

        choice = input(
            "\nEnter your choice (1/2/3/4): "
        ).strip()

        if choice in ["1", "2", "3", "4"]:
            return choice

        print(
            "Invalid input. "
            "Please enter 1, 2, 3, or 4."
        )


# ------------------------------------------
# Save stock
# ------------------------------------------

def save_stock(stock, filename):
    """Save the stock dictionary to stock.txt."""

    try:

        with open(filename, "w") as file:

            for name, quantity in stock.items():

                file.write(
                    f"{name}:{quantity}\n"
                )

        print("\nStock saved successfully.")

    except Exception as error:

        print("Error saving the stock file.")
        print(error)


# ------------------------------------------
# Main program
# ------------------------------------------

def main():

    filename = "stock.txt"

    # Read stock file
    stock = read_stock(filename)

    # Infinite loop
    while True:

        # Print menu
        print_menu()

        # Get valid choice
        choice = get_menu_choice()

        # Option 1: Add
        if choice == "1":

            add_stock(stock)

        # Option 2: Remove
        elif choice == "2":

            remove_stock(stock)

        # Option 3: Show
        elif choice == "3":

            show_stock(stock)

        # Option 4: Exit
        elif choice == "4":

            save_stock(stock, filename)

            print("Exiting the program...")
            break


# ------------------------------------------
# Start program
# ------------------------------------------

if __name__ == "__main__":
    main()

from PIL import Image
from google.colab import files
from IPython.display import display

# Upload image
files.upload()

# Open image
image = Image.open("img.png")

# Convert to grayscale
bw_image = image.convert("L")

# Display image
display(bw_image)